import type { Metadata } from 'next'
import './globals.css'
import { ModeProvider } from '@/context/ModeContext'
import { Poppins } from 'next/font/google'

const poppins  = Poppins({weight: ["400", "500", "600", "700"],subsets: ['latin']})

export const metadata: Metadata = {
  title: 'PortFolio',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <ModeProvider>
        {children}
    </ModeProvider>
  )
}

export default RootLayout;
